// <auto-generated />
namespace VideoForU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieModelModificationId15092020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieModelModificationId15092020));
        
        string IMigrationMetadata.Id
        {
            get { return "202009150444055_MovieModelModificationId15092020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
