// <auto-generated />
namespace VideoForU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GenreAddedWithReferenceInMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreAddedWithReferenceInMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "202009130625507_GenreAddedWithReferenceInMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
